<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <PlatformTarget>x86</PlatformTarget>
    <UseWPF>true</UseWPF>
    <EnableDefaultApplicationDefinition>true</EnableDefaultApplicationDefinition>
    <EnableDefaultPageItems>true</EnableDefaultPageItems>
  </PropertyGroup>

  <ItemGroup>
    <ApplicationDefinition Include="src\App.xaml" />
  </ItemGroup>

</Project>
